### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by abdulrehman1937** [silviazuffi/smalst#10]
Kindly guide me how did you generate pose coordinates. Actually i am working on new dataset how can i achieve this?

**Comment by silviazuffi** [comment]
Poses have been generated by sampling a 3D pose prior. The 3D pose prior is a Multivariate Gaussian over a set of poses recovered from data.
You can use the poses that are already in the dataset, or learn a Multivariate Gaussian model using the provided poses in the training set.
