### ISSUE TITLE
can you share the reconstruction code?

### ISSUE THREAD

**Issue by seyeeet** [silviazuffi/smalst#14]
it possible to share the code that is used for reconstruction?

**Comment by silviazuffi** [comment]
Hi, you can look at the function smal_eval.py in the root directory

**Comment by seyeeet** [comment]
@silviazuffi  
Hello, 
thank you for your reply.
I looked into the smal._eval.py, I found mask_img which is saving, but if I understand it correctly it is not the reconstruction.
by reconstruction I mean the code that produces the results here:
![image](https://user-images.githubusercontent.com/62394093/94705267-d8673500-030e-11eb-9ab3-0b6d25c1e7b3.png)

Please feel free to point me to the right section if I am missing something.
Thanks

**Comment by silviazuffi** [comment]
Hi,
If you should look at line 194-195 in SMAL_eval.py
