### ISSUE TITLE
Use the model for other animals

### ISSUE THREAD

**Issue by arianme** [silviazuffi/smalst#25]
Hi Silvia,

In your paper it is mentioned that this model can be used on other animals as well. I am having difficulties to do so. I crop my image and enter the bounding box in the crop file. When running the evaluation script the result for my own image is not adequate.

Would you kindly outline the steps necessary to use this model on new images of other type of animals?
I would appreciate your help!

Thanks,
Best,
Arian

**Comment by silviazuffi** [comment]
Hi,

The model can be used for other animals in the sense that you can train a network for other species. 
This does not mean that the model trained for the Grevy’s zebra can be used on other animals directly.

Best,

Silvia

**Comment by arianme** [comment]
I see, thank you for your quick reply.

Best,
Arian
