### ISSUE TITLE
Input Video to the model

### ISSUE THREAD

**Issue by ras3791** [silviazuffi/smalst#9]
Is there any support for testing model using video file?

**Comment by silviazuffi** [comment]
No, this is a method that assumes the input is a bounding box of a Grevy’s zebra in his natural environment.

**Comment by ras3791** [comment]
Thanks for the quick reply. I have one more query how are you generating the processed images from full size?

**Comment by silviazuffi** [comment]
Hi,
I got the images with the bounding boxes from our coauthor Tanya Berger Wolf from WildBook https://www.wildbook.org/doku.php <https://www.wildbook.org/doku.php>

**Comment by ras3791** [comment]
Thanks!
